server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instance
          uri: https://github.com/franco22bellido/microservices-Java-Introduction
          search-paths: config-data
  application:
    name: config-server